import { useState, useEffect } from "react";
import { Bookmark, Trash2, Download, ExternalLink, FileText, Search } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";
import { useLocation } from "wouter";

export interface SavedQuery {
  id: string;
  query: string;
  summary: string;
  confidenceScore: number;
  savedAt: string;
  language?: string;
  persona?: string;
  sources: { scheme: string; source: string }[];
}

export const BOOKMARKS_KEY = "policybot_bookmarks";

export function getSavedBookmarks(): SavedQuery[] {
  try {
    return JSON.parse(localStorage.getItem(BOOKMARKS_KEY) ?? "[]");
  } catch {
    return [];
  }
}

export function saveBookmark(bookmark: SavedQuery) {
  const existing = getSavedBookmarks();
  const updated = [bookmark, ...existing.filter((b) => b.id !== bookmark.id)];
  localStorage.setItem(BOOKMARKS_KEY, JSON.stringify(updated));
}

export function deleteBookmark(id: string) {
  const existing = getSavedBookmarks();
  localStorage.setItem(BOOKMARKS_KEY, JSON.stringify(existing.filter((b) => b.id !== id)));
}

function exportAsText(bookmark: SavedQuery) {
  const content = [
    `PolicyBot — Saved Query`,
    `Saved: ${new Date(bookmark.savedAt).toLocaleString()}`,
    ``,
    `QUERY`,
    bookmark.query,
    ``,
    `SUMMARY`,
    bookmark.summary,
    ``,
    `CONFIDENCE SCORE: ${Math.round(bookmark.confidenceScore * 100)}%`,
    ``,
    `SOURCES`,
    ...bookmark.sources.map((s) => `• ${s.scheme}: ${s.source}`),
  ].join("\n");

  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `policybot-${bookmark.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

function exportAsPDF(bookmark: SavedQuery) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>PolicyBot — ${bookmark.query}</title>
      <style>
        body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #1a1a2e; line-height: 1.6; }
        h1 { font-size: 18px; color: #0f4c75; border-bottom: 2px solid #0f4c75; padding-bottom: 8px; }
        h2 { font-size: 14px; color: #1b6ca8; margin-top: 20px; }
        .meta { font-size: 12px; color: #666; margin-bottom: 20px; }
        .score { display: inline-block; background: #e8f4f8; padding: 2px 8px; border-radius: 4px; font-size: 12px; }
        .source { margin: 6px 0; font-size: 12px; color: #333; }
        .footer { margin-top: 40px; font-size: 11px; color: #999; }
      </style>
    </head>
    <body>
      <h1>PolicyBot — Policy Consultation</h1>
      <div class="meta">Saved: ${new Date(bookmark.savedAt).toLocaleString()} | Confidence: <span class="score">${Math.round(bookmark.confidenceScore * 100)}%</span></div>
      <h2>Query</h2>
      <p>${bookmark.query}</p>
      <h2>Summary</h2>
      <p>${bookmark.summary}</p>
      <h2>Sources</h2>
      ${bookmark.sources.map((s) => `<div class="source">• <strong>${s.scheme}</strong>: ${s.source}</div>`).join("")}
      <div class="footer">Generated by PolicyBot — AI-powered Government Policy Assistant</div>
    </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.print();
}

export function Bookmarks() {
  const [bookmarks, setBookmarks] = useState<SavedQuery[]>([]);
  const [search, setSearch] = useState("");
  const { toast } = useToast();
  const [, setLocation] = useLocation();

  useEffect(() => {
    setBookmarks(getSavedBookmarks());
  }, []);

  function handleDelete(id: string) {
    deleteBookmark(id);
    setBookmarks(getSavedBookmarks());
    toast({ title: "Bookmark removed", description: "The saved query has been deleted." });
  }

  function handleClearAll() {
    localStorage.removeItem(BOOKMARKS_KEY);
    setBookmarks([]);
    toast({ title: "All bookmarks cleared" });
  }

  const filtered = bookmarks.filter(
    (b) =>
      b.query.toLowerCase().includes(search.toLowerCase()) ||
      b.summary.toLowerCase().includes(search.toLowerCase())
  );

  if (bookmarks.length === 0) {
    return (
      <div className="space-y-8 animate-in fade-in duration-500 max-w-4xl mx-auto">
        <div className="flex flex-col space-y-4">
          <div className="inline-flex items-center justify-center p-3 bg-amber-500/10 rounded-full w-14 h-14 mb-2">
            <Bookmark className="w-8 h-8 text-amber-600" />
          </div>
          <h1 className="text-3xl font-bold tracking-tight">My Policies</h1>
          <p className="text-muted-foreground text-lg">Save any policy consultation result to access it offline or export it as a document.</p>
        </div>
        <div className="text-center py-20 bg-muted/20 rounded-lg border border-dashed">
          <Bookmark className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <h3 className="text-lg font-semibold mb-2">No saved policies yet</h3>
          <p className="text-muted-foreground mb-6">Run a consultation and click "Save" to bookmark the results here.</p>
          <Button onClick={() => setLocation("/")} data-testid="button-go-consult">
            <Search className="mr-2 h-4 w-4" />
            Start a Consultation
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in duration-500 max-w-4xl mx-auto">
      <div className="flex flex-col space-y-4">
        <div className="inline-flex items-center justify-center p-3 bg-amber-500/10 rounded-full w-14 h-14 mb-2">
          <Bookmark className="w-8 h-8 text-amber-600" />
        </div>
        <h1 className="text-3xl font-bold tracking-tight">My Policies</h1>
        <p className="text-muted-foreground text-lg">
          Your saved policy consultations. Export as PDF or text, or remove entries you no longer need.
        </p>
      </div>

      <div className="flex gap-4 items-center">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search saved queries..."
            className="pl-9"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            data-testid="input-search-bookmarks"
          />
        </div>
        <Button variant="outline" size="sm" onClick={handleClearAll} className="text-destructive hover:text-destructive" data-testid="button-clear-all">
          <Trash2 className="mr-2 h-4 w-4" />
          Clear All
        </Button>
      </div>

      <div className="space-y-4">
        {filtered.map((bookmark) => (
          <Card key={bookmark.id} className="border-l-4 border-l-amber-400 shadow-sm hover:shadow-md transition-shadow" data-testid={`card-bookmark-${bookmark.id}`}>
            <CardHeader className="pb-2 bg-muted/20">
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <CardTitle className="text-lg line-clamp-2">{bookmark.query}</CardTitle>
                  <CardDescription className="mt-1 text-xs flex items-center gap-3 flex-wrap">
                    <span>{new Date(bookmark.savedAt).toLocaleString()}</span>
                    {bookmark.persona && <Badge variant="outline" className="text-[10px]">{bookmark.persona}</Badge>}
                    {bookmark.language && <Badge variant="outline" className="text-[10px]">{bookmark.language.toUpperCase()}</Badge>}
                    <span className="text-primary font-medium">Confidence: {Math.round(bookmark.confidenceScore * 100)}%</span>
                  </CardDescription>
                </div>
                <Button
                  variant="ghost"
                  size="icon"
                  className="shrink-0 text-destructive hover:text-destructive"
                  onClick={() => handleDelete(bookmark.id)}
                  data-testid={`button-delete-${bookmark.id}`}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            </CardHeader>
            <CardContent className="pt-4 space-y-4">
              <p className="text-sm text-muted-foreground leading-relaxed">{bookmark.summary}</p>

              {bookmark.sources.length > 0 && (
                <div className="flex flex-wrap gap-2">
                  {bookmark.sources.map((s, i) => (
                    <a
                      key={i}
                      href={s.source}
                      target="_blank"
                      rel="noreferrer"
                      className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
                    >
                      <ExternalLink className="w-3 h-3" />
                      {s.scheme}
                    </a>
                  ))}
                </div>
              )}

              <div className="flex gap-2 pt-1">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => exportAsText(bookmark)}
                  data-testid={`button-export-text-${bookmark.id}`}
                >
                  <Download className="mr-1.5 h-3.5 w-3.5" />
                  Export Text
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => exportAsPDF(bookmark)}
                  data-testid={`button-export-pdf-${bookmark.id}`}
                >
                  <FileText className="mr-1.5 h-3.5 w-3.5" />
                  Export PDF
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}

        {filtered.length === 0 && (
          <div className="text-center py-12 bg-muted/20 rounded-lg border border-dashed">
            <p className="text-muted-foreground">No bookmarks match your search.</p>
          </div>
        )}
      </div>
    </div>
  );
}
